name: deploy

on:
  push: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout backend
        uses: actions/checkout@v2
      - name: checkout frontend
        uses: actions/checkout@v2
        with: 
          repository: couch-coding/heroku-actions-front
          path: ./frontend
      - run: |
          ls -al
          cd frontend
          ls -al

        